---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: debian-8
  - name: ubuntu-14.04
  - name: ubuntu-16.04

suites:
  - name: defalut 
    run_list:
      - recipe[devpio]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
